# Generated by Django 4.0.6 on 2022-07-07 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_category_post_slug'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='post',
    #         name='category',
    #         field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
    #         preserve_default=False,
    #     ),
    # ]
