# Generated by Django 4.0.6 on 2022-07-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_slug_post_slug'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='post',
        #     name='category',
        # ),
    ]
