# Generated by Django 4.0.6 on 2022-07-16 08:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_post_image_alter_post_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
